-- Feeding plan lifecycle + richer meal logs
ALTER TABLE "Feeding" ADD COLUMN IF NOT EXISTS "objective" TEXT;
ALTER TABLE "Feeding" ADD COLUMN IF NOT EXISTS "targetWeightKg" DOUBLE PRECISION;
ALTER TABLE "Feeding" ADD COLUMN IF NOT EXISTS "startDate" TEXT;
ALTER TABLE "Feeding" ADD COLUMN IF NOT EXISTS "reviewDate" TEXT;
ALTER TABLE "Feeding" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE "FeedingLog" ADD COLUMN IF NOT EXISTS "reason" TEXT;
ALTER TABLE "FeedingLog" ADD COLUMN IF NOT EXISTS "notes" TEXT;
